var chooselight = [obj_wall_light_L,obj_wall_light_L,obj_wall_light_L,obj_wall_light_L,obj_wall_light_L,obj_wall_light_L,obj_wall_light_L,obj_wall_light_L,obj_wall_light_L_weak,obj_wall_light_L_weak,obj_wall_light_L_weak,obj_wall_light_L_weak,obj_wall_light_L_weak,obj_wall_light_R_off,obj_wall_light_R_off,obj_wall_light_R_off,obj_wall_light_R_off]
var select = obj_wall_light_R_off
var newlight = instance_create_layer(x,y,"dark",select)
